export const URI = 'https://kiemdien.herokuapp.com/api/admin';
//https://kiemdien.herokuapp.com/api/admin
//http://localhost:4000/api/admin

export const GET_ERRORS = 'GET_ERRORS';
export const CLEARN_ERRORS = 'CLEARN_ERRORS';

export const LOG_IN = 'LOGIN';
export const LOG_OUT = 'LOGOUT';

export const GET_CITYS = 'GET_CITYS';

export const GET_CURRENT_ACCOUNT = 'GET_CURRENT_ACCOUNT';

export const GET_USERS = 'GET_USERS';
export const DELETE_USERS = 'DELETE_USERS';
export const CREATE_USER = 'CREATE_USER';

export const GET_USER_CONDITION_STATUS_TRUE = 'GET_USER_CONDITION_STATUS_TRUE';

export const UPLOAD_PICTURE_ACCOUNT = 'UPLOAD_PICTURE_ACCOUNT';
export const REMOVE_PICTURE_ACCOUNT = 'REMOVE_PICTURE_ACCOUNT';
export const UPDATE_INFO_ACCOUNT = 'UPDATE_INFO_ACCOUNT';
export const UPDATE_PASSWORD_ACCOUNT = 'UPDATE_PASSWORD_ACCOUNT';

export const GET_CLASSES = 'GET_CLASSES';
export const ADD_ClASS = 'ADD_ClASS';
export const DELETE_CLASS = 'DELETE_CLASS';

export const GET_CLASS_BY_ID = 'GET_CLASS_BY_ID';
export const UPDATE_INFO_CLASS_BY_ID = 'UPDATE_INFO_CLASS_BY_ID';
export const UPDATE_AVATAR_CLASS_BY_ID = 'UPDATE_AVATAR_CLASS_BY_ID';
export const REMOVE_AVATAR_CLASS_BY_ID = 'REMOVE_AVATAR_CLASS_BY_ID';
export const IMPORT_DSSV_CLASS_BY_ID = 'IMPORT_DSSV_CLASS_BY_ID';
export const ADD_CLASS_MEMBER_BY_ID = 'ADD_CLASS_MEMBER_BY_ID';
export const EDIT_CLASS_MEMBER_BY_ID = 'EDIT_CLASS_MEMBER_BY_ID';
export const DELETE_CLASS_MEMBER_BY_ID = 'DELETE_CLASS_MEMBER_BY_ID';
export const CHANGE_MANAGER_PERSON = 'CHANGE_MANAGER_PERSON';
export const REMOVE_MANAGER_PERSON = 'REMOVE_MANAGER_PERSON';

export const GET_CLASS_ASSIGNES = 'GET_CLASS_ASSIGNES';

export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';

export const LOADING_LOCAL = 'LOADING_LOCAL';
export const LOADING_LOCAL_SUCCESS = 'LOADING_LOCAL_SUCCESS';

export const OPEN_NOTIFY = 'OPEN_NOTIFY';
export const CLOSE_NOTIFY = 'CLOSE_NOTIFY';

export const GET_CLASS_LATEST = 'GET_CLASS_LATEST';
export const GET_ASSIGNES_LATEST = 'GET_ASSIGNES_LATEST';
export const STATISTICAL_TOTAL_CLASS = 'STATISTICAL_TOTAL_CLASS';
export const STATISTICAL_TOTAL_USER = 'STATISTICAL_TOTAL_USER';
export const STATISTICAL_TOTAL_MEMBER = 'STATISTICAL_TOTAL_MEMBER';

export const GET_CLASS_PRESENCES = 'GET_CLASS_PRESENCES';

export const GET_PRESENCES_DETAIL = 'GET_PRESENCES_DETAIL';
export const DELETE_PRESENCES_MEMBER = 'DELETE_PRESENCES_MEMBER';

export const SEARCH_TASK = 'SEARCH_TASK';
export const SEARCH_TASK_DRAW = 'SEARCH_TASK_DRAW';
export const FILTER_TASK = 'FILTER_TASK';
export const CLEARN_TASK = 'CLEARN_TASK';
export const CLEARN_TASK_DRAW = 'CLEARN_TASK_DRAW';